###
POST http://localhost:9000/api/proveedores HTTP/1.1
Content-Type: application/json

{
    "client_id" : "MP12345",
    "email" : "miguelpalma@macropay.mx",
    "rfc" : "PALM961201TN2",
    "city" : "Campeche",
    "country" : "MX",
    "cp" : "24500",
    "name" : "Mikky Enterprise",
    "region" : "NA",
    "street" : "Calle 20",
    "surname" : "Mikky SA de CV",
    "title" : "Mikky",
    "regimen_fiscal" : "RN2"
}

###
GET http://localhost:9000/api/proveedores HTTP/1.1

###
GET http://localhost:9000/api/proveedores/635007c877996ceb56b13564 HTTP/1.1

###
PUT http://localhost:9000/api/proveedores/635007c877996ceb56b13564 HTTP/1.1
Content-Type: application/json

{
    "client_id" : "DP12345",
    "email" : "david.poot@macropay.mx",
    "rfc" : "DEIVID901002TN2",
    "city" : "Cancun",
    "country" : "MX",
    "cp" : "30500",
    "name" : "Deivid Enterprise",
    "region" : "SA",
    "street" : "Calle 50",
    "surname" : "Deivid SA de CV",
    "title" : "Deivid",
    "regimen_fiscal" : "DN2"
}

###
DELETE http://localhost:9000/api/proveedores/635007c877996ceb56b13564 HTTP/1.1